{% set version = "4.9.3" %}

package:
  name: lxml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/lxml/lxml-{{ version }}.tar.gz
  sha256: 48628bd53a426c9eb9bc066a923acaa0878d1e86129fd5359aee99285f4eed9c
  patches:
    - fix-initialization.patch

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - pkg-config
  host:
    - libxml2
    - python
    - pip
    - cython <3
    - libxslt
    - zlib
  run:
    - python

test:
  imports:
    - lxml
    - lxml.etree
    - lxml.objectify
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://lxml.de/
  license: BSD-3-Clause and LicenseRef-ElementTree
  license_file: LICENSES.txt
  summary: Pythonic binding for the C libraries libxml2 and libxslt.
  description: |
    The lxml XML toolkit is a Pythonic binding for the C libraries libxml2 and
    libxslt. It is unique in that it combines the speed and XML feature
    completeness of these libraries with the simplicity of a native Python API,
    mostly compatible but superior to the well-known ElementTree API.
  doc_url: http://lxml.de/index.html#documentation
  dev_url: https://github.com/lxml/lxml
  doc_source_url: https://github.com/lxml/lxml/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
    - zklaus
